name: Deploy OfficeListFind to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build JAR file
      run: |
        mvn clean package -DskipTests

    - name: Set up Docker permissions
      run: |
        sudo chmod 666 /var/run/docker.sock

    - name: Build Docker Image
      run: |
        docker build -t office-list-find:latest .
        sudo docker save office-list-find:latest > office-list-find.tar
        sudo chmod 644 office-list-find.tar

    - name: Transfer Docker Image
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: office-list-find.tar
        target: /home/ec2-user/

    - name: SSH to EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker load < /home/ec2-user/office-list-find.tar
          sudo docker stop office-list-find || true
          sudo docker rm office-list-find || true
          sudo docker run -d -p 8080:8080 --name office-list-find office-list-find:latest
          rm /home/ec2-user/office-list-find.tar
